[env:esp32p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
upload_port = /dev/tty.usbmodem5B5E1346401
monitor_port = /dev/tty.usbmodem5B5E1346401
monitor_filters = esp32_exception_decoder, time
board_upload.flash_size = 32MB
board_build.partitions = partitions.csv
